{
  imports =
    [
      ./boot.nix
      ./console.nix
      ./environment.nix
      ./il8n.nix
      ./fonts.nix
      ./networking.nix
      ./nh.nix
      ./nix.nix
      ./programs.nix
      ./services.nix
      ./system.nix
      ./time.nix
      ./user.nix
      ./xserver.nix
    ];
}
